import os

DEBUG = True
PORT = 5025
HOST = '0.0.0.0'

SECRET_KEY = 'YOUR_SECRET_KEY_HERE'

EVEONLINE_CLIENT_SECRET = os.environ['EVEONLINE_CLIENT_SECRET']
EVEONLINE_CLIENT_ID = os.environ['EVEONLINE_CLIENT_ID']
